#!/bin/sh
set -e

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

BASE=varvar
VARVAR=/opt/varvar/$BASE
VARVAR_SSD_PIDFILE=/var/run/$BASE-ssd.pid
VARVAR_LOGFILE=/var/log/$BASE.log

. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
    . /etc/default/$BASE
fi

case "$1" in
    start)
        touch "$VARVAR_LOGFILE"
        log_begin_msg "Starting: $BASE"
        start-stop-daemon --start \
            --background \
            --no-close \
            --exec "$VARVAR" \
            --pidfile "$VARVAR_SSD_PIDFILE" \
            --make-pidfile \
            >> "$VARVAR_LOGFILE" 2>&1
        log_end_msg $?
        ;;
    stop)
        log_begin_msg "Stopping: $BASE"
        start-stop-daemon --stop \
            --pidfile "$VARVAR_SSD_PIDFILE" \
            --retry 10
        log_end_msg $?
        ;;
    restart)
        varvar_pid=`cat "$VARVAR_SSD_PIDFILE" 2>/dev/null`
        [ -n "$varvar_pid" ] \
            && ps -p $varvar_pid > /dev/null 2>&1 \
            && $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$VARVAR_SSD_PIDFILE" "$VARVAR" "$BASE"
        ;;
    *)
        echo "Usage: service docker {start|stop|restart|status}"
        exit 1
        ;;
esac
